# Generated by Django 3.0.6 on 2021-09-21 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rangeCategory', '0002_auto_20210921_0557'),
        ('outlet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='customer_fee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rangeCategory.Category'),
            preserve_default=False,
        ),
    ]
