# Generated by Django 3.0.6 on 2021-09-29 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outlet',
            old_name='outlet_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='outlet',
            old_name='customer_fee',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='outlet',
            old_name='outlet_officer',
            new_name='officer',
        ),
        migrations.RenameField(
            model_name='outlet',
            old_name='outlet_name',
            new_name='range_category_customer_fee',
        ),
        migrations.RenameField(
            model_name='outlet',
            old_name='transfer_fee',
            new_name='range_category_transfer_fee',
        ),
        migrations.RenameField(
            model_name='outlet',
            old_name='withdrawal_fee',
            new_name='range_category_withdrawal_fee',
        ),
    ]
