# Generated by Django 3.0.6 on 2021-09-21 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0002_outlet_customer_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outlet',
            name='customer_fee',
        ),
    ]
