# Generated by Django 3.0.6 on 2021-09-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0003_remove_outlet_customer_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='customer_fee',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outlet',
            name='transfer_fee',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outlet',
            name='withdrawal_fee',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
