# Generated by Django 3.0.6 on 2021-09-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rangeCategory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='range',
            name='charge_type',
        ),
        migrations.AddField(
            model_name='category',
            name='range_type',
            field=models.CharField(choices=[('customer fee for withdrawal', 'Customer Fee For Withdrawal'), ('pos fee for withdrawal', 'Pos Fee For Withdrawal'), ('pos fee for transfer', 'Pos Fee For Transfer')], default=None, max_length=255),
            preserve_default=False,
        ),
    ]
