# Generated by Django 3.0.6 on 2021-09-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rangeCategory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='range_type',
            field=models.CharField(choices=[('customer_fee', 'Customer Fee For Withdrawal'), ('pos_fee_on_withdrawal', 'Pos Fee For Withdrawal'), ('pos_fee_on_transfer', 'Pos Fee For Transfer')], max_length=205),
        ),
    ]
