# Generated by Django 3.0.6 on 2021-09-01 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rangeCategory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='date_added',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='range',
            old_name='in_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='range',
            old_name='date_added',
            new_name='created_at',
        ),
    ]
