# Generated by Django 3.0.6 on 2021-08-21 21:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rangeCategory', '0004_auto_20210821_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
