# Generated by Django 3.0.6 on 2021-08-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rangeCategory', '0005_category_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='date_added',
            field=models.DateField(),
        ),
    ]
