# Generated by Django 3.0.6 on 2021-08-21 22:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rangeCategory', '0007_auto_20210821_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 8, 21, 22, 16, 17, 687267, tzinfo=utc)),
        ),
    ]
