# Generated by Django 3.0.6 on 2021-09-21 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_officers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Officers',
        ),
    ]
