# Generated by Django 3.2.6 on 2021-08-18 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_is_verified_user_isverified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fullName',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='isVerified',
            new_name='is_verified',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
